service: my-express-application
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getContent:
    handler: index.handler
    events:
      - http: 'GET /api/{proxy+}'